### ISSUE TITLE
Corriger les docs disant qu'il n'est pas possible de lancer un enregistrement avec l'enregistreur intégré à la gamebuino via le code, car c'est en fait possible

### ISSUE THREAD

**Issue by moeenio** [iw4rr10r/gb-meta-screen-recorder#1]
https://community.gamebuino.com/t/meta-screen-recorder-by-steph/802/2?u=locness3

@iw4rr10r

**Comment by m1cr0lab** [comment]
Merci de ta vigilance... J'avais complètement oublié (à l'époque) de reformuler ce court passage pour nuancer mon discours. C'est désormais chose faite.
